/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'broadcast': '&#xe9b9;',
            'add-square-outline': '&#xe9bd;',
            'plus-square-outline': '&#xe9bd;',
            'add-square': '&#xe9be;',
            'plus-square': '&#xe9be;',
            'create-outline': '&#xe9bf;',
            'compose-outline': '&#xe9bf;',
            'create': '&#xe9c0;',
            'compose': '&#xe9c0;',
            'chevron-forward-circle': '&#xe9ba;',
            'chevron-right-circle': '&#xe9ba;',
            'chevron-back-circle': '&#xe9bb;',
            'chevron-left-circle': '&#xe9bb;',
            'flag': '&#xe9bc;',
            'trash': '&#xe9b0;',
            'bin': '&#xe9b0;',
            'cloud-upload-outline': '&#xe9b1;',
            'copy': '&#xe9b2;',
            'clipboard': '&#xe9b2;',
            'qr-code': '&#xe9b3;',
            'scan-qr': '&#xe9b4;',
            'discount': '&#xe9b5;',
            'promo': '&#xe9b5;',
            'external-link': '&#xe9b6;',
            'reorder': '&#xe9b7;',
            'upload': '&#xe9b8;',
            'trophy': '&#xe9ad;',
            'catalog': '&#xe9ae;',
            'collection': '&#xe9ae;',
            'dashboard-grid': '&#xe9af;',
            'volume-high-mute': '&#xe99c;',
            'volume-high-off': '&#xe99c;',
            'volume-mute': '&#xe99d;',
            'volume-high-mute-outline': '&#xe9ab;',
            'volume-high-off-outline': '&#xe9ab;',
            'volume-mute-outline': '&#xe9ac;',
            'download': '&#xe9aa;',
            'cloud': '&#xe9a9;',
            'send': '&#xe929;',
            'cloud-download': '&#xe9a7;',
            'cloud-download-outline': '&#xe9a8;',
            'list': '&#xe94c;',
            'people-outline': '&#xe967;',
            'videocam-outline': '&#xe995;',
            'video-outline': '&#xe995;',
            'volume-low-outline': '&#xe999;',
            'chat-bubble-outline': '&#xe9a5;',
            'ellipsis-vertical-circle': '&#xe9a6;',
            'more-android-circle': '&#xe9a6;',
            'bag-outline': '&#xe901;',
            'bag-add-outline': '&#xe902;',
            'bag-plus-outline': '&#xe902;',
            'chat-bubble-ellipses': '&#xe903;',
            'chat-bubble-ellipses-outline': '&#xe904;',
            'add': '&#xe905;',
            'plus': '&#xe905;',
            'add-circle': '&#xe906;',
            'plus-circle': '&#xe906;',
            'add-circle-outline': '&#xe907;',
            'plus-circle-outline': '&#xe907;',
            'alert-circle': '&#xe908;',
            'exclamation-circle': '&#xe908;',
            'alert-circle-outline': '&#xe909;',
            'exclamation-circle-outline': '&#xe909;',
            'arrow-back': '&#xe90a;',
            'arrow-left': '&#xe90a;',
            'arrow-down': '&#xe90b;',
            'arrow-forward': '&#xe90c;',
            'arrow-right': '&#xe90c;',
            'arrow-up': '&#xe90d;',
            'attach': '&#xe90e;',
            'bag': '&#xe90f;',
            'bag-add': '&#xe900;',
            'bag-plus': '&#xe900;',
            'bookmark': '&#xe910;',
            'bookmark-outline': '&#xe911;',
            'calendar': '&#xe912;',
            'calendar-number': '&#xe913;',
            'calendar-date': '&#xe913;',
            'call': '&#xe914;',
            'camera': '&#xe915;',
            'camera-outline': '&#xe916;',
            'camera-reverse': '&#xe917;',
            'camera-flip': '&#xe917;',
            'camera-reverse-outline': '&#xe918;',
            'camera-flip-outline': '&#xe918;',
            'caret-back': '&#xe919;',
            'caret-left': '&#xe919;',
            'caret-down': '&#xe91a;',
            'caret-forward': '&#xe91b;',
            'caret-right': '&#xe91b;',
            'caret-up': '&#xe91c;',
            'cart': '&#xe91d;',
            'cart-outline': '&#xe91e;',
            'chat-bubble': '&#xe91f;',
            'checkmark': '&#xe920;',
            'check': '&#xe920;',
            'tick': '&#xe920;',
            'checkmark-circle': '&#xe921;',
            'check-circle': '&#xe921;',
            'tick-circle': '&#xe921;',
            'checkmark-done': '&#xe922;',
            'check-done': '&#xe922;',
            'double-check': '&#xe922;',
            'double-tick': '&#xe922;',
            'tick-done': '&#xe922;',
            'chevron-back': '&#xe923;',
            'chevron-left': '&#xe923;',
            'chevron-down': '&#xe924;',
            'chevron-forward': '&#xe925;',
            'chevron-right': '&#xe925;',
            'chevron-up': '&#xe926;',
            'close': '&#xe927;',
            'x': '&#xe927;',
            'close-circle': '&#xe928;',
            'x-circle': '&#xe928;',
            'code': '&#xe92a;',
            'code-slash': '&#xe92b;',
            'crop': '&#xe92c;',
            'document': '&#xe92d;',
            'doc': '&#xe92d;',
            'document-text': '&#xe92e;',
            'doc-text': '&#xe92e;',
            'ellipsis-horizontal': '&#xe92f;',
            'more-ios': '&#xe92f;',
            'ellipsis-horizontal-circle': '&#xe930;',
            'more-ios-circle': '&#xe930;',
            'ellipsis-horizontal-circle-outline': '&#xe931;',
            'more-iOS-circle-outline': '&#xe931;',
            'ellipsis-vertical': '&#xe932;',
            'more-android': '&#xe932;',
            'exit-outline': '&#xe933;',
            'log-out': '&#xe933;',
            'sign-out': '&#xe933;',
            'expand': '&#xe934;',
            'eye': '&#xe935;',
            'eye-off': '&#xe936;',
            'flash': '&#xe937;',
            'flash-off': '&#xe938;',
            'folder': '&#xe939;',
            'footsteps': '&#xe93a;',
            'gift': '&#xe93b;',
            'globe': '&#xe93c;',
            'globe-outline': '&#xe93d;',
            'grid': '&#xe93e;',
            'group': '&#xe93f;',
            'group-add': '&#xe940;',
            'headset': '&#xe941;',
            'headphones': '&#xe941;',
            'heart': '&#xe942;',
            'love': '&#xe942;',
            'heart-outline': '&#xe943;',
            'love-outline': '&#xe943;',
            'help-circle': '&#xe944;',
            'question-mark-circle': '&#xe944;',
            'help-circle-outline': '&#xe945;',
            'question-mark-circle-outline': '&#xe945;',
            'id-card': '&#xe946;',
            'image': '&#xe947;',
            'picture': '&#xe947;',
            'information-circle': '&#xe948;',
            'info-circle': '&#xe948;',
            'information-circle-outline': '&#xe949;',
            'info-circle-outline': '&#xe949;',
            'language': '&#xe94a;',
            'translate': '&#xe94a;',
            'link': '&#xe94b;',
            'hyperlink': '&#xe94b;',
            'location': '&#xe94d;',
            'map-pin': '&#xe94d;',
            'lock-closed': '&#xe94e;',
            'locked': '&#xe94e;',
            'lock-open': '&#xe94f;',
            'unlock': '&#xe94f;',
            'logo-WhatsApp': '&#xe950;',
            'whatsapp': '&#xe950;',
            'mail': '&#xe951;',
            'mail-outline': '&#xe952;',
            'male': '&#xe953;',
            'man': '&#xe954;',
            'map': '&#xe955;',
            'menu': '&#xe956;',
            'mic': '&#xe957;',
            'microphone': '&#xe957;',
            'mic-off': '&#xe958;',
            'microphone-off': '&#xe958;',
            'mute': '&#xe958;',
            'moon': '&#xe959;',
            'do-not-disturb': '&#xe959;',
            'musical-note': '&#xe95a;',
            'music-note': '&#xe95a;',
            'musical-notes': '&#xe95b;',
            'music-notes': '&#xe95b;',
            'navigate': '&#xe95c;',
            'nav': '&#xe95c;',
            'navigate-outline': '&#xe95d;',
            'nav-outline': '&#xe95d;',
            'notification': '&#xe95e;',
            'bell': '&#xe95e;',
            'notification-off': '&#xe95f;',
            'bell-off': '&#xe95f;',
            'options': '&#xe960;',
            'adjust': '&#xe960;',
            'paper-plane': '&#xe961;',
            'pause': '&#xe962;',
            'pause-circle': '&#xe963;',
            'people': '&#xe964;',
            'people-circle': '&#xe965;',
            'people-circle-outlline': '&#xe966;',
            'person': '&#xe968;',
            'person-circle': '&#xe969;',
            'person-circle-outline': '&#xe96a;',
            'play': '&#xe96b;',
            'play-back': '&#xe96c;',
            'play-previous': '&#xe96c;',
            'play-back-circle': '&#xe96d;',
            'play-previous-circle': '&#xe96d;',
            'play-circle': '&#xe96e;',
            'play-circle-outline': '&#xe96f;',
            'play-forward': '&#xe970;',
            'play-forward-circle': '&#xe971;',
            'play-skip-back': '&#xe972;',
            'play-skip-previous': '&#xe972;',
            'play-skip-back-circle': '&#xe973;',
            'play-skip-previous-circle': '&#xe973;',
            'podium': '&#xe978;',
            'price-tag': '&#xe979;',
            'reader': '&#xe97a;',
            'refresh': '&#xe97b;',
            'refresh-circle': '&#xe97c;',
            'reload': '&#xe97d;',
            'reload-circle': '&#xe97e;',
            'remove': '&#xe97f;',
            'minus': '&#xe97f;',
            'remove-circle': '&#xe980;',
            'minus-circle': '&#xe980;',
            'remove-circle-outline': '&#xe981;',
            'minus-circle-outline': '&#xe981;',
            'rocket': '&#xe982;',
            'scan': '&#xe983;',
            'search': '&#xe984;',
            'search-outline': '&#xe985;',
            'settings': '&#xe986;',
            'gear': '&#xe986;',
            'share-android': '&#xe987;',
            'share-ios': '&#xe988;',
            'shield-checkmark': '&#xe989;',
            'shield-check': '&#xe989;',
            'shield-tick': '&#xe989;',
            'star': '&#xe98a;',
            'star-half': '&#xe98b;',
            'star-outline': '&#xe98c;',
            'stop': '&#xe98d;',
            'text': '&#xe98e;',
            'time': '&#xe98f;',
            'clock': '&#xe98f;',
            'time-outline': '&#xe990;',
            'clock-outline': '&#xe990;',
            'verified': '&#xe991;',
            'videocam': '&#xe992;',
            'video': '&#xe992;',
            'videocam-off': '&#xe993;',
            'video-off': '&#xe993;',
            'videocam-off-outline': '&#xe994;',
            'video-off-outline': '&#xe994;',
            'volume-high': '&#xe996;',
            'volume-high-outline': '&#xe997;',
            'volume-low': '&#xe998;',
            'volume-medium': '&#xe99a;',
            'volume-medium-outline': '&#xe99b;',
            'volume-off': '&#xe99e;',
            'volume-off-outline': '&#xe99f;',
            'warning': '&#xe9a0;',
            'wifi': '&#xe9a1;',
            'wifi-off': '&#xe9a2;',
            'wifi-problem': '&#xe9a3;',
            'woman': '&#xe9a4;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/icon-display-/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
